language: julia
os:
  - linux
julia:
  - 1.1
  - 1.2
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
    - downloads
env:
  global:
    - BINARYBUILDER_DOWNLOADS_CACHE=downloads
    - BINARYBUILDER_AUTOMATIC_APPLE=false
  matrix:
    - TARGET=x86_64-linux-gnu
    - TARGET=i686-linux-gnu
    - TARGET=x86_64-apple-darwin14
    - TARGET=x86_64-unknown-freebsd
    - TARGET=x86_64-w64-mingw32
    - TARGET=i686-w64-mingw32
sudo: required
before_script:
  - julia -e 'using Pkg; pkg"add BinaryProvider"; pkg"add BinaryBuilder#master"; Pkg.build()'
script:
  - julia build_tarballs.jl

jobs:
  include:
    - stage: deploy
      if: "tag =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+(a|b|rc)?[0-9]*$"
      julia: 1.2
      sudo: required
      cache:
        timeout: 1000
        directories:
          - downloads
      sudo: required
      before_script:
        - julia -e 'using Pkg; pkg"add BinaryProvider"; pkg"add BinaryBuilder#master"; Pkg.build()'
      script:
        - julia build_tarballs.jl
      deploy:
        provider: releases
        api_key:
          secure: R5SdhBrVMMNA+Xa5ahYdW14vaMtNrRrn3D3vp9/yUTRf+u+fm2+B49tjNaWcITLm6Bx0H7WyHKrfpCxyk5yoY2owL8X1TBm8bWqeVXiH+2SIV3B13zoAozdZAXnEONFoLYjgiFy+uQzXJs57CmI7oEqjM8lx4q9BO17G/+tTvcQUvA8a1uE08PztBs/rVM1pNRYnL+wHb9X7jaeL+BfP2X3fhwfvva5t03gtNLLU/FMjC3z2nAaVyX0oETX4uVdlxthO0aWwcnZAOK5b7ignFOZD1eq1HYreTMS85vgRAAmnKr0JPujqZqF/lcvUek7kGtqXExMIrcHkpQn33oznPiAksl1sSNKiGrKwa+olni/45aHa3gWCoX3gmYX6DZy2ivkCthehWtKJNqU09OT7nM5MrI+vmpc1hZJrwJHkOeo+xMo8BoXqtFwRd7UezxJiWytzWOHTRXwrqE5kFbXt4pvNviQ2Ti1wxn2xt2gzugpgvyQ7gZSN/LVb46uDFZwdWBOc/fmlXDpBoGqLXp1p8J5zhkWiTMdZp38b6rAPGMFsEy0yUGLtG3OC8Rul3mYBlzP916m0fGel5WUo3daR9Xc387H42Nhx9qdwt6ScxnkxoWotCe5lqtfcyoWwZqvTgWiL+Dc0FVk9cJJ9Ibs/RH7qWEhFp+fehN0hB2yvE/w=
        skip_cleanup: true
        file_glob: true
        file: products/*
        on:
          repo: unkcpz/SpglibBuilder
          tags: true
